services:
  app:
    build: .
    ports:
      - '2025:4000'
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=4000
      - FRONTEND_URL=http://localhost:4000
    command: ["node", "server/index.js"]
